# Generated by Django 3.0.4 on 2020-03-21 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_art_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='yearCreated',
        ),
        migrations.AddField(
            model_name='art',
            name='dateTaken',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Taken'),
            preserve_default=False,
        ),
    ]
