# Generated by Django 3.0.4 on 2020-03-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200325_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='present',
            field=models.CharField(choices=[('Y', 'Yes'), ('A', 'At Risk'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
