# Generated by Django 3.0.4 on 2020-03-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_art_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('At Risk', 'At Risk'), ('No', 'No')], default='Yes', max_length=7),
        ),
    ]
